### PR TITLE
make Duration::convert const

### PR DESCRIPTION
**Pull request by TDHolmes**
Can be const as of rust 1.57

### CODE REVIEW

**Comment by TDHolmes** [comment]
@korken89 are you open to adding an MSRV to this crate of 1.57? If so I can add it to `package.rust-version` in the `Cargo.toml` and add a CI step to verify it with [`cargo-msrv`](https://github.com/foresterre/cargo-msrv)

**Comment by TDHolmes** [comment]
Adding MSRV check in CI is a bit gross at the moment actually.. see https://github.com/TDHolmes/embedded-profiling/pull/7 and https://github.com/foresterre/cargo-msrv/issues/224

**Review by korken89 — APPROVED** [review]

**Comment by korken89** [comment]
I think it's fine as is. :)
I can look into MSRV in the future, for now this library is practically only guarantees to work on the latest `stable`.

**Comment by korken89** [comment]
bors merge

**Pull request merged**
