### PR TITLE
mirror From methods

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by korken89** [comment]
Hi @burrbull , thanks for the PR!! Sorry this has gone under my radar.

Could you write a small motivation to this change? 
I'm not quite following what it is fixing other than adding more shorthands.

Thanks!

**Comment by burrbull** [comment]
This just makes code slightly clearer and similar to `From` / `Into` way. It is strange to have `into` but don't have `from` and vise versa.

**Comment by korken89** [comment]
Alright, looks good! :+1: 

Could you expand the tests with the new APIs?

**Comment by burrbull** [comment]
> Alright, looks good! +1
> 
> Could you expand the tests with the new APIs?

I've added several.
Writing docs and tests make me cry.

**Review by korken89 — APPROVED** [review]
Thanks for the effort!

**Comment by korken89** [comment]
I'll fix adding more tests in the API test!

**Pull request merged**
