### PR TITLE
ceil rounded durations

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by korken89** [comment]
Thanks, looks like a a sane addition! Could you add tests for it and I'll merge?

**Comment by burrbull** [comment]
What do you think about naming? Should I change something?

**Comment by burrbull** [comment]
rebased

**Review by korken89 — APPROVED** [review]

**Comment by korken89** [comment]
Thanks for the effort!

I'll look into making a release including this during the weekend.

**Pull request merged**
