### PR TITLE
Fix TimerRateU32 and TimerRateU64 to be Rate instead of Duration

### LINKED ISSUE #31: Why are TimerRateU32 and TimerRateU64 based on Duration instead of Rate?
https://github.com/korken89/fugit/blob/bcc0a1d7ef0a74c2cbb13d50def4461166869c4c/src/aliases.rs#L111-L117

Maybe there's a specific reason TimerRateU32 and TimerRateU64 are Durations instead of Rate? Or is this just a typo?
I'll submit a PR just in case.

### PR DESCRIPTION
**Pull request by haata**
- Likely a typo
- Fixes #31

### CODE REVIEW

**Review by korken89 — APPROVED** [review]
Thank you for finding this!

**Comment by korken89** [comment]
Could you have a look at adding a test and fixing the failing CI build?

**Comment by haata** [comment]
Sure, I'll take a stab at it.

**Comment by haata** [comment]
Is this the kind of test you're looking for?

**Review by korken89 — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
